### PR TITLE
Droplet for Curation via XRDP

### PR DESCRIPTION
**Pull request by zoidy**
Scripts for configuring a Droplet for XRDP access via SSH tunnel

### CODE REVIEW

**Review by astrochun — COMMENTED** [review]
Overall this is a good `ansible` playbook with a fair amount of documentation. However, given how complex it is, I think it would make more sense to have this as an `ansible` role as that provides separate documentation and packages in a manner that makes it easy to understand and reuse. Here's an example for our [swap space creator](https://github.com/ualibraries/redata_iac/tree/master/ansible/roles/do-ubuntu-swapspace).
This does not need to occur now, but perhaps at some point. I'm OK with keeping it a single ansible playbook for now.

I would recommend:
1. The use of vars input when (e.g., `create_user_name: {{ username }}`) as that does not require manually changing the script and ensures consistency.
2. I would use built-in commands as much as possible. For example, instead of `useradd` via `cmd`, I would use the [`user` module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html)
3. It was not immediately clear what some of the binary files are. For example the .lnk is the shortcut, but that was not obvious.

**Comment by zoidy** [comment]
Thanks for the suggestions. Variables is something I'd like to do as it would make things more elegant. The reason I used shell commands instead of the user module is that the proper hashed password can be generated in one line. Do you have any suggestions for how to do it elegantly with the user module?

**Comment by astrochun** [comment]
> Thanks for the suggestions. Variables is something I'd like to do as it would make things more elegant. The reason I used shell commands instead of the user module is that the proper hashed password can be generated in one line. Do you have any suggestions for how to do it elegantly with the user module?

The user module does discuss how to hash password. I tried a few different ways but ended up going with this [option](https://github.com/ualibraries/redata_iac/blob/d84625ab1a0150d8279ebf8ea034bf575d38acad/ansible/roles/redata-account-create/tasks/main.yml#L6).

The advantage is that you don't have to hash it before passing it in. You just specify it on the CLI, and it hashes it and uploads it.

I would suggest checking out PR #28 as I managed to change an `ansible` playbook to a role with documentation and default variables. In fact, I think this role could be used in your code for account creation.

**Comment by zoidy** [comment]
I did look at the user module docs but the link discussing hashing was broken. Thanks for the snippet, it looks like a good fit. I'll tackle this when I have some time

**Comment by astrochun** [comment]
> I did look at the user module docs but the link discussing hashing was broken. Thanks for the snippet, it looks like a good fit. I'll tackle this when I have some time

Yea, it looks like they changed some pieces of FAQ docs (removed them) and now all these links are broken.
I think this [SO](https://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible) thread shows all the options, although keep in mind some have been outdated with newer ansible version and newer python

**Comment by zoidy** [comment]
Now addressed by PR #41

**Pull request closed without merging**
